name: Build and push to Azure registry

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - 
        name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to private registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: '${{ secrets.REGISTRY_URL }}/t7d_products:${{ steps.prep.outputs.BUILD_ID }}'
          cache-from: 'type=registry,ref=${{ secrets.REGISTRY_URL }}/t7d_products:buildcache'
          cache-to: 'type=registry,ref=${{ secrets.REGISTRY_URL }}/t7d_products:buildcache,mode=max'
